apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  replicas: 1
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
      - name: subscription
        image: zoomcamp-model:3.13.10-hw10
        resources:
          requests:
            memory: "64Mi" # Correct: Mi for Mebibytes
            cpu: "100m"
          limits:
            memory: "256Mi" # <-- CORRECTED: Changed "256mb" to "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080