[project]
name = "midterm"
version = "0.1.0"
description = "Water Potability Prediction Service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.0",
    "uvicorn>=0.38.0",
]
